name: EileenClassRoom

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    networks:
      - internal
    volumes:
      - ecr_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  ecr_backend:
    image: ghcr.io/bnnj/eileenclassroom-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - postgres_password
      - secret_key
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD_FILE: /run/secrets/postgres_password

      SECRET_KEY_FILE: /run/secrets/secret_key

      ENVIRONMENT: ${ENVIRONMENT:?set ENVIRONMENT}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      CORS_ORIGINS: ${CORS_ORIGINS:-}
    networks:
      - internal
      - proxy
    expose:
      - "8000"


  ecr_frontend:
    image: ghcr.io/bnnj/eileenclassroom-frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "80"

volumes:
  ecr_db_data:

networks:
  internal:
    name: ecr-internal
  proxy:
    external: true
    name: proxy

secrets:
  postgres_password:
    file: ./secrets/postgres_password
  secret_key:
    file: ./secrets/secret_key
